{{- if .Values.externalSecret.enabled -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "image-registry-metrics-exporter.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "image-registry-metrics-exporter.labels" . | nindent 4 }}
spec: {{- .Values.externalSecret.spec | toYaml | trim | nindent 2  }}
{{- end }}
