{{- if .Values.irme.credentials.value }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "image-registry-metrics-exporter.fullname" . }}-secret-token
  labels: {{- include "image-registry-metrics-exporter.labels" . | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "image-registry-metrics-exporter.annotations" . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  token: {{ .Values.irme.credentials.value | b64enc | quote }}
  {{- end }}
