{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "image-registry-metrics-exporter.fullname" . }}
  labels: {{- include "image-registry-metrics-exporter.labels" . | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "image-registry-metrics-exporter.annotations" . | nindent 4 }}
  {{- end }}
  {{- end }}
