{{- if .Values.serviceMonitor.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "image-registry-metrics-exporter.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    chart: {{ template "image-registry-metrics-exporter.chart" . }}
    app: {{ template "image-registry-metrics-exporter.name" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    {{- if .Values.serviceMonitor.labels }}
    {{- toYaml .Values.serviceMonitor.labels | nindent 4 }}
    {{- end }}
spec:
  endpoints:
  - interval: {{ .Values.serviceMonitor.interval }}
    {{- if .Values.serviceMonitor.scrapeTimeout }}
    scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
    {{- end }}
    port: {{ .Values.service.metricsPort.name }}
    path: {{ .Values.service.metricsPort.path }}
  selector:
    matchLabels:
      {{- include "image-registry-metrics-exporter.selectorLabels" . | nindent 6 }}
  {{- end }}
