---
name: Lint (Golang)
on: # yamllint disable-line rule:truthy
  pull_request:
    types: [opened, synchronize]
    paths:
      - .github/workflows/lint.golang.yml
      - go.*
      - cmd/**
      - pkg/**

jobs:
  golangci-lint:
    name: Golang CI lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        with:
          # renovate: datasource=golang-version
          go-version: '1.20'
          check-latest: true
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - uses: golangci/golangci-lint-action@639cd343e1d3b897ff35927a75193d57cfcba299 # v3.6.0
        with:
          # renovate: datasource=github-releases depName=golangci/golangci-lint
          version: v1.53.3
