---
name: Security (Container)
on: # yamllint disable-line rule:truthy
  pull_request:
    types: [opened, synchronize]
    paths:
      - .github/workflows/security.container.yml
      - Dockerfile

jobs:
  # Analyze statically Helm charts to identify any policy violations.
  checkov:
    name: Checkov
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3.4.0
      - uses: actions/setup-python@bd6b4b6205c4dbad673328db7b31b7fab9e241c0 # v4.6.1
        with:
          python-version: '3.8'
          check-latest: true

      - uses: bridgecrewio/checkov-action@a6b06158ca30c135b38291f4fa0da67d188ca8f4
        with:
          framework: dockerfile
          skip_check: CKV_DOCKER_2
      - uses: github/codeql-action/upload-sarif@a589d4087ea22a0a48fc153d1b461886e262e0f2 # tag=codeql-bundle-20221211
        if: always()
        with:
          category: checkov-helm
          sarif_file: results.sarif
