---
name: Security (Container)
on: # yamllint disable-line rule:truthy
  pull_request:
    types: [opened, synchronize]
    paths:
      - .github/workflows/security.container.yml
      - Dockerfile

jobs:
  # Analyze statically Helm charts to identify any policy violations.
  checkov:
    name: Checkov
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: actions/setup-python@39cd14951b08e74b54015e9e001cdefcf80e669f # v5.1.1
        with:
          python-version: '3.8'
          check-latest: true

      - uses: bridgecrewio/checkov-action@a6b06158ca30c135b38291f4fa0da67d188ca8f4
        with:
          framework: dockerfile
          skip_check: CKV_DOCKER_2
      - uses: github/codeql-action/upload-sarif@896079047b4bb059ba6f150a5d87d47dde99e6e5 # codeql-bundle-20221211
        if: always()
        with:
          category: checkov-helm
          sarif_file: results.sarif
