---
name: Test (Helm)
on: # yamllint disable-line rule:truthy
  pull_request:
    types: [opened, synchronize]
    paths:
      - .github/workflows/test.helm.yml
      - charts/**
  push:
    branches: [main]

jobs:
  # Test all charts using the official chart-testing CLI.
  chart_testing:
    name: Chart testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0
      - uses: azure/setup-helm@5119fcb9089d432beecbf79bb2c7915207344b78 # tag=v3.5
      - uses: actions/setup-python@39cd14951b08e74b54015e9e001cdefcf80e669f # v5.1.1
        with:
          python-version: '3.9'
          check-latest: true
      - uses: helm/chart-testing-action@e6669bcd63d7cb57cb4380c33043eebe5d111992 # v2.6.1
      - uses: helm/kind-action@99576bfa6ddf9a8e612d83b513da5a75875caced # v1.9.0

      - name: Run chart-testing (install)
        if: github.event_name == 'pull_request'
        run: ct install --target-branch ${{ github.event.pull_request.base.ref }} --helm-extra-set-args '--set=image.tag=ci'
      - name: Run chart-testing (install)
        if: github.event_name == 'push'
        run: ct install --all --helm-extra-set-args '--set=image.tag=ci'
