---
name: Test (Helm)
on: # yamllint disable-line rule:truthy
  pull_request:
    types: [opened, synchronize]
    paths:
      - .github/workflows/test.helm.yml
      - charts/**
  push:
    branches: [main]

jobs:
  # Test all charts using the official chart-testing CLI.
  chart_testing:
    name: Chart testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with:
          fetch-depth: 0
      - uses: azure/setup-helm@5119fcb9089d432beecbf79bb2c7915207344b78 # tag=v3.5
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: '3.14'
          check-latest: true
      - uses: helm/chart-testing-action@e6669bcd63d7cb57cb4380c33043eebe5d111992 # v2.6.1
      - uses: helm/kind-action@ef37e7f390d99f746eb8b610417061a60e82a6cc # v1.14.0

      - name: Run chart-testing (install)
        if: github.event_name == 'pull_request'
        run: ct install --target-branch ${{ github.event.pull_request.base.ref }} --helm-extra-set-args '--set=image.tag=ci'
      - name: Run chart-testing (install)
        if: github.event_name == 'push'
        run: ct install --all --helm-extra-set-args '--set=image.tag=ci'
