---
name: Test (Golang)
on: # yamllint disable-line rule:truthy
  pull_request:
    types: [opened, synchronize]
    paths:
      - .github/workflows/test.golang.yml
      - go.*
      - cmd/**
      - pkg/**
  push:
    branches: [main]

jobs:
  go-test:
    name: Golang test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed # v5.1.0
        with:
          # renovate: datasource=golang-version
          go-version: '1.22'
          check-latest: true
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: szenius/set-timezone@ce9c440bc3af4f51b28d7ef7e5c47ee8f26c8dcb # v1.2
        with:
          timezoneLinux: "Europe/Paris"
      - name: Run golang tests
        run: go test -v -race -covermode=atomic -coverprofile=coverage.out ./...
      - name: Archive code coverage results
        uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
        with:
          name: golang-coverage-report
          path: coverage.out
          retention-days: 1

  codecov:
    name: Codecov
    runs-on: ubuntu-latest
    needs: [go-test]
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2
        with:
          name: golang-coverage-report

      - uses: codecov/codecov-action@e28ff129e5465c2c0dcc6f003fc735cb6ae0c673 # v4.5.0
